### ISSUE TITLE
log native code

### ISSUE THREAD

**Issue by manang** [atom/libchromiumcontent#688]
Hi,
I want to test my modification in libchromiumcontent, used inside electron, and I want to print something on screen to understand if the flow is correct.
I'm trying with std::cout, but I don't see traces.
do you have tricks to adopt?
Thank you very much

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
