### ISSUE TITLE
libcrhomiumcontent and read/write files

### ISSUE THREAD

**Issue by manang** [atom/libchromiumcontent#689]
Hi,
I'm trying to modify webrtc part and I need to know if webrtc is able to read/write files.
thank you for your help
Angelo

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
