### ISSUE TITLE
Regenerate out-x64 and out

### ISSUE THREAD

**Issue by manang** [atom/libchromiumcontent#692]
Hi, I'm trying to compile with electron script ./script/bootstrap.py -v --build_release_libcc libchromiumcontent dependency.
the problem is that I need to delete the dir out and out-x64, generated with ninja.
I want to regerate them because I've changed the xcode version and there are issues about the includes path.
I tried with clean, but it has deleted libchromiumcontent repo, with my modifications.
do you have a command to do it?
Thank you very much
Angelo

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
