### ISSUE TITLE
Access denied when downloaing the asset.

### ISSUE THREAD

**Issue by ervinewell** [atom/libchromiumcontent#699]
When I download release assets through **https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/${platform}/${commit}/libchromiumcontent.zip**, whatever commit I use,    there's a hint:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>5B6693BED7E2E883</RequestId>
<HostId>
Q97ZqKuzCFXzrlV1Ya5Yha3P6uW3uifUEmt+5yzSubs9kjU1BkxRBCTYE9/aSZGu/lanHv2ZrkA=
</HostId>
</Error>
```
target electron version: 2.0.x
link I use: **https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/osx/x64/768f52340da3a67a68fb138683909b8b292f470c/libchromiumcontent-static.zip**

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
