### ISSUE TITLE
bootstrap : TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by squalou** [atom/libchromiumcontent#761]
Hi,

a small typo apparently in script/lib/util.py : a tab should be replaced by 4 spaces.

```code
Traceback (most recent call last):
  File "./script/bootstrap", line 8, in <module>
    import lib.util as util
  File "/home/pronecker/src/libchromiumcontent/script/lib/util.py", line 76
    vsvarsall = "C:\\Program Files (x86)\\Microsoft Visual Studio {0}\\VC\\vcvarsall.bat".format(vs_version)
```

**Comment by miniak** [comment]
Can you please create a PR with a fix?

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
